project:
  type: website
  output-dir: docs

website:
  title: 'MKDocs'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  page-footer: 
    center: "© 2024 Your Name. All rights reserved."

format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

  format:
  html:
    theme: litera
    css: styles.scss

